language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pwd
  - pip install .
  - pip install "pytest>=3.10.0"
# command to run tests
script:
- pwd
- postmancli -h
- pytest -v
